module,execution_time (sec),success,timestamp,error,error_short
cowidev.vax.batch.argentina,24.97,True,2023-08-03T07:00:33,,
cowidev.vax.batch.australia,,,2023-08-03T07:00:08,,
cowidev.vax.batch.austria_old,,,2023-08-03T07:00:08,,
cowidev.vax.batch.belgium,8.03,True,2023-08-03T07:00:16,,
cowidev.vax.batch.bolivia,3.9,True,2023-08-03T07:00:12,,
cowidev.vax.batch.canada,5.04,False,2023-08-03T07:03:13,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 282, in main
    Canada().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 270, in export
    df = df.pipe(self.pipeline, df_man)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 250, in pipeline
    .pipe(self.pipe_make_monotonic)[
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/canada.py"", line 230, in pipe_make_monotonic
    df = df.pipe(self.make_monotonic, max_removed_rows=self.max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/utils/base.py"", line 120, in make_monotonic
    return mkm(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 23, in make_monotonic
    return make_monotonic_new(df, column_date, column_metrics, max_removed_rows)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/utils.py"", line 96, in make_monotonic_new
    raise Exception(
Exception: 2 chunks of lengths 36, 29 would be NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26', '2023-06-15']. Location(s) affected: {'Canada'}
","2 chunks of lengths 36, 29 would be NaNed for metric people_vaccinated. That is more than maximum allowed (22) by make_monotonic() - check the data. Check dates ['2023-01-26', '2023-06-15']. Location(s) affected: {'Canada'}"
cowidev.vax.batch.chile,1.33,True,2023-08-03T07:00:09,,
cowidev.vax.batch.czechia,50.1,True,2023-08-03T07:00:58,,
cowidev.vax.batch.denmark,,,2023-08-03T07:00:08,,
cowidev.vax.batch.ecdc,110.06,True,2023-08-03T07:01:58,,
cowidev.vax.batch.ecuador,,,2023-08-03T07:00:08,,
cowidev.vax.batch.estonia,0.86,True,2023-08-03T07:00:09,,
cowidev.vax.batch.france,6.11,True,2023-08-03T07:00:14,,
cowidev.vax.batch.germany,0.63,True,2023-08-03T07:00:09,,
cowidev.vax.batch.greece,30.74,True,2023-08-03T07:00:39,,
cowidev.vax.batch.hong_kong,29.23,True,2023-08-03T07:00:37,,
cowidev.vax.batch.indonesia,,,2023-08-03T07:00:08,,
cowidev.vax.batch.ireland,3.89,True,2023-08-03T07:00:12,,
cowidev.vax.batch.israel,0.11,False,2023-08-03T07:03:13,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/israel.py"", line 189, in main
    Israel().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/israel.py"", line 175, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/israel.py"", line 21, in read
    data = request_json(self.source_url, verify=False)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/scraping.py"", line 107, in request_json
    return json.loads(text)
  File ""/usr/lib/python3.10/json/__init__.py"", line 346, in loads
    return _default_decoder.decode(s)
  File ""/usr/lib/python3.10/json/decoder.py"", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ""/usr/lib/python3.10/json/decoder.py"", line 355, in raw_decode
    raise JSONDecodeError(""Expecting value"", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 2 (char 3)
",Expecting value: line 3 column 2 (char 3)
cowidev.vax.batch.italy,28.58,True,2023-08-03T07:00:37,,
cowidev.vax.batch.japan,9.73,False,2023-08-03T07:03:23,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 375, in main
    Japan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 359, in export
    df = self.read().pipe(self.pipeline_base)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 71, in read
    df_latest = self.read_latest().pipe(self.pipe_read_latest)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 100, in read_latest
    self._read_latest_booster(),
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 211, in _read_latest_booster
    df = self._read_xlsx(
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/japan.py"", line 233, in _read_xlsx
    raise ValueError(f""Unknown sheets: {sheets_unknown}"")
ValueError: Unknown sheets: {'5.8以降接種_一般接種（４回目）', '６回目_一般接種回数', '5.8以降接種_一般接種（５回目）', '５回目_総接種回数', '５回目_一般接種回数', '5.8以降接種_一般接種（６回目）', '６回目_総接種回数', '5.8以降接種_一般接種（３回目）', '5.8以降接種_総接種回数'}
","Unknown sheets: {'5.8以降接種_一般接種（４回目）', '６回目_一般接種回数', '5.8以降接種_一般接種（５回目）', '５回目_総接種回数', '５回目_一般接種回数', '5.8以降接種_一般接種（６回目）', '６回目_総接種回数', '5.8以降接種_一般接種（３回目）', '5.8以降接種_総接種回数'}"
cowidev.vax.batch.jersey,3.32,True,2023-08-03T07:00:11,,
cowidev.vax.batch.latvia,179.97,True,2023-08-03T07:03:08,,
cowidev.vax.batch.lithuania,6.2,True,2023-08-03T07:00:14,,
cowidev.vax.batch.luxembourg,2.44,True,2023-08-03T07:00:10,,
cowidev.vax.batch.malaysia,1.34,True,2023-08-03T07:00:09,,
cowidev.vax.batch.malta,1.14,True,2023-08-03T07:00:09,,
cowidev.vax.batch.netherlands,,,2023-08-03T07:00:08,,
cowidev.vax.batch.new_zealand,1.97,False,2023-08-03T07:03:25,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/new_zealand.py"", line 119, in main
    NewZealand().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/new_zealand.py"", line 114, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/new_zealand.py"", line 43, in read
    df = read_xlsx_from_url(link, sheet_name=""Date"")
  File ""/home/owid/covid-19-data/scripts/src/cowidev/utils/web/download.py"", line 47, in read_xlsx_from_url
    df = pd.read_excel(tmp.name, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/util/_decorators.py"", line 311, in wrapper
    return func(*args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/excel/_base.py"", line 364, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/io/excel/_base.py"", line 1195, in __init__
    raise ValueError(
ValueError: Excel file format cannot be determined, you must specify an engine manually.
","Excel file format cannot be determined, you must specify an engine manually."
cowidev.vax.batch.norway,0.56,True,2023-08-03T07:00:09,,
cowidev.vax.batch.peru,0.84,True,2023-08-03T07:03:26,,
cowidev.vax.batch.portugal,,,2023-08-03T07:00:08,,
cowidev.vax.batch.romania,42.09,True,2023-08-03T07:00:50,,
cowidev.vax.batch.saudi_arabia,10.74,True,2023-08-03T07:00:19,,
cowidev.vax.batch.singapore,3.37,True,2023-08-03T07:00:11,,
cowidev.vax.batch.slovakia,64.18,True,2023-08-03T07:01:12,,
cowidev.vax.batch.slovenia,2.99,True,2023-08-03T07:00:11,,
cowidev.vax.batch.south_korea,11.86,False,2023-08-03T07:03:38,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 209, in main
    SouthKorea().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 191, in export
    df_base = self.read().pipe(self.pipeline_base)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 109, in pipeline_base
    .pipe(self.pipe_check_metrics)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/batch/south_korea.py"", line 92, in pipe_check_metrics
    raise ValueError(f""Metric {dose} for 'all' is not equal to the sum over all vaccines (2% tolerance)."")
ValueError: Metric dose_1 for 'all' is not equal to the sum over all vaccines (2% tolerance).
",Metric dose_1 for 'all' is not equal to the sum over all vaccines (2% tolerance).
cowidev.vax.batch.spc,37.74,True,2023-08-03T07:00:46,,
cowidev.vax.batch.sweden,27.13,True,2023-08-03T07:00:36,,
cowidev.vax.batch.switzerland,102.04,True,2023-08-03T07:01:51,,
cowidev.vax.batch.trinidad_and_tobago,5.91,True,2023-08-03T07:00:15,,
cowidev.vax.batch.ukraine,,,2023-08-03T07:00:09,,
cowidev.vax.batch.united_kingdom,28.12,True,2023-08-03T07:00:37,,
cowidev.vax.batch.united_states,24.06,True,2023-08-03T07:00:33,,
cowidev.vax.batch.uruguay,1.2,True,2023-08-03T07:00:11,,
cowidev.vax.batch.zimbabwe,2.29,True,2023-08-03T07:00:13,,
cowidev.vax.incremental.africacdc,,,2023-08-03T07:00:11,,
cowidev.vax.incremental.antigua_barbuda,,,2023-08-03T07:00:11,,
cowidev.vax.incremental.aruba,2.47,True,2023-08-03T07:00:13,,
cowidev.vax.incremental.austria,,,2023-08-03T07:00:11,,
cowidev.vax.incremental.azerbaijan,,,2023-08-03T07:00:11,,
cowidev.vax.incremental.bahrain,,,2023-08-03T07:00:11,,
cowidev.vax.incremental.bangladesh,91.71,True,2023-08-03T07:01:43,,
cowidev.vax.incremental.barbados,,,2023-08-03T07:00:11,,
cowidev.vax.incremental.brazil,0.57,True,2023-08-03T07:00:12,,
cowidev.vax.incremental.bulgaria,12.38,True,2023-08-03T07:00:24,,
cowidev.vax.incremental.china,27.93,True,2023-08-03T07:00:39,,
cowidev.vax.incremental.costa_rica,,,2023-08-03T07:00:12,,
cowidev.vax.incremental.croatia,0.53,True,2023-08-03T07:00:12,,
cowidev.vax.incremental.cuba,1.34,False,2023-08-03T07:03:39,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/cuba.py"", line 82, in main
    Cuba().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/cuba.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/cuba.py"", line 29, in read
    return self._parse_data(soup)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/cuba.py"", line 34, in _parse_data
    ""date"": self._parse_date(soup),
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/cuba.py"", line 41, in _parse_date
    date_str = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
",'NoneType' object has no attribute 'group'
cowidev.vax.incremental.curacao,,,2023-08-03T07:00:12,,
cowidev.vax.incremental.cyprus,6.33,True,2023-08-03T07:00:18,,
cowidev.vax.incremental.dominican_republic,14.43,False,2023-08-03T07:03:53,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 112, in main
    DominicanRepublic().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 68, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 26, in read
    metrics = self._parse_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 35, in _parse_metrics
    metric_candidates = _find_potential_metrics(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 91, in _find_potential_metrics
    h3 = _find_h3(driver)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/dominican_republic.py"", line 81, in _find_h3
    raise ValueError(""More than one element found!"")
ValueError: More than one element found!
",More than one element found!
cowidev.vax.incremental.el_salvador,16.17,True,2023-08-03T07:00:29,,
cowidev.vax.incremental.faeroe_islands,2.5,True,2023-08-03T07:00:16,,
cowidev.vax.incremental.fiji,0.0,True,2023-08-03T07:00:14,,
cowidev.vax.incremental.finland,0.48,True,2023-08-03T07:00:15,,
cowidev.vax.incremental.gabon,,,2023-08-03T07:00:14,,
cowidev.vax.incremental.georgia,9.82,True,2023-08-03T07:00:24,,
cowidev.vax.incremental.greenland,,,2023-08-03T07:00:15,,
cowidev.vax.incremental.guatemala,,,2023-08-03T07:00:15,,
cowidev.vax.incremental.guernsey,,,2023-08-03T07:00:15,,
cowidev.vax.incremental.hungary,97.12,True,2023-08-03T07:01:52,,
cowidev.vax.incremental.iceland,6.99,True,2023-08-03T07:00:22,,
cowidev.vax.incremental.india,3.53,True,2023-08-03T07:00:19,,
cowidev.vax.incremental.iran,,,2023-08-03T07:00:16,,
cowidev.vax.incremental.isle_of_man,3.26,True,2023-08-03T07:00:19,,
cowidev.vax.incremental.jamaica,12.03,True,2023-08-03T07:00:30,,
cowidev.vax.incremental.kazakhstan,13.62,True,2023-08-03T07:00:32,,
cowidev.vax.incremental.kosovo,,,2023-08-03T07:00:19,,
cowidev.vax.incremental.kyrgyzstan,7.15,True,2023-08-03T07:00:26,,
cowidev.vax.incremental.laos,1.76,True,2023-08-03T07:03:55,,
cowidev.vax.incremental.macao,,,2023-08-03T07:00:22,,
cowidev.vax.incremental.moldova,,,2023-08-03T07:00:22,,
cowidev.vax.incremental.monaco,102.52,True,2023-08-03T07:02:04,,
cowidev.vax.incremental.mongolia,3.25,True,2023-08-03T07:00:25,,
cowidev.vax.incremental.montenegro,1.93,True,2023-08-03T07:00:26,,
cowidev.vax.incremental.morocco,,,2023-08-03T07:00:24,,
cowidev.vax.incremental.myanmar,,,2023-08-03T07:00:24,,
cowidev.vax.incremental.nepal,,,2023-08-03T07:00:24,,
cowidev.vax.incremental.north_macedonia,,,2023-08-03T07:00:24,,
cowidev.vax.incremental.northern_cyprus,5.0,True,2023-08-03T07:00:29,,
cowidev.vax.incremental.paho,85.43,False,2023-08-03T07:05:21,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 195, in main
    PAHO().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 190, in export
    df = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 167, in pipeline
    df.pipe(self.pipe_check_columns)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 5430, in pipe
    return com.pipe(self, func, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/venv/lib/python3.10/site-packages/pandas/core/common.py"", line 471, in pipe
    return func(obj, *args, **kwargs)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/paho.py"", line 122, in pipe_check_columns
    raise ValueError(f""Missing column fields: {columns_missing}. Present columns are: {df.columns}"")
ValueError: Missing column fields: {'2nd additional dose', '1st additional dose', 'First dose', 'Single dose', 'Second dose', 'Country code', 'Total doses', 'Country/ Territory'}. Present columns are: Index(['date,location,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_interpolated,new_people_vaccinated_interpolated,new_vaccinations_smoothed,new_people_vaccinated_smoothed', 'date'], dtype='object')
","Missing column fields: {'2nd additional dose', '1st additional dose', 'First dose', 'Single dose', 'Second dose', 'Country code', 'Total doses', 'Country/ Territory'}. Present columns are: Index(['date,location,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_interpolated,new_people_vaccinated_interpolated,new_vaccinations_smoothed,new_people_vaccinated_smoothed', 'date'], dtype='object')"
cowidev.vax.incremental.pakistan,,,2023-08-03T07:00:26,,
cowidev.vax.incremental.philippines,,,2023-08-03T07:00:26,,
cowidev.vax.incremental.poland,3.66,True,2023-08-03T07:00:29,,
cowidev.vax.incremental.qatar,,,2023-08-03T07:00:26,,
cowidev.vax.incremental.russia,37.48,True,2023-08-03T07:01:04,,
cowidev.vax.incremental.saint_lucia,,,2023-08-03T07:00:29,,
cowidev.vax.incremental.serbia,9.6,True,2023-08-03T07:00:38,,
cowidev.vax.incremental.south_africa,,,2023-08-03T07:00:29,,
cowidev.vax.incremental.spain,28.29,True,2023-08-03T07:00:57,,
cowidev.vax.incremental.sri_lanka,,,2023-08-03T07:00:29,,
cowidev.vax.incremental.suriname,15.92,True,2023-08-03T07:00:45,,
cowidev.vax.incremental.taiwan,6.18,False,2023-08-03T07:05:27,"Traceback (most recent call last):
  File ""/home/owid/covid-19-data/scripts/src/cowidev/cmd/commons/get.py"", line 47, in run
    module.main()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 186, in main
    Taiwan().export()
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 172, in export
    data = self.read().pipe(self.pipeline)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 38, in read
    df = self._parse_table(url_pdf)
  File ""/home/owid/covid-19-data/scripts/src/cowidev/vax/incremental/taiwan.py"", line 68, in _parse_table
    raise ValueError(f""Table 1: format has changed! It has shape {df.shape} instead of {shape_expected}"")
ValueError: Table 1: format has changed! It has shape (44, 4) instead of (42, 4)
","Table 1: format has changed! It has shape (44, 4) instead of (42, 4)"
cowidev.vax.incremental.thailand,7.25,True,2023-08-03T07:00:37,,
cowidev.vax.incremental.turkey,,,2023-08-03T07:00:30,,
cowidev.vax.incremental.united_arab_emirates,,,2023-08-03T07:00:30,,
cowidev.vax.incremental.vietnam,,,2023-08-03T07:00:30,,
cowidev.vax.incremental.who,35.97,True,2023-08-03T07:01:06,,
cowidev.vax.incremental.zambia,2.15,True,2023-08-03T07:00:34,,
